# Useful aliases
alias c='clear'
alias e='exit'
alias ..='cd ..'
alias ls='ls -CF --color=auto'
alias ll='ls -lisa --color=auto'
alias mkdir='mkdir -pv'
alias free='free -mt'
alias ps='ps auxf'
alias psgrep='ps aux | grep -v grep | grep -i -e VSZ -e'
alias wget='wget -c'
alias histg='history | grep'
alias myip='curl ipv4.icanhazip.com'
alias grep='grep --color=auto'

alias v='nvim'
alias cfp='v ~/.config/polybar/config.ini'
alias cfpm='v ~/.config/polybar/modules.ini'
alias cft='v ~/.config/termite/config'
alias cfbs='v ~/.config/bspwm/bspwmrc'
alias cfsx='v ~/.config/sxhkd/sxhkdrc'
alias cfb='v ~/.bashrc'
alias cfba='v ~/.bash_aliases'
alias cfal='v ~/.config/alacritty/alacritty.yml'
alias pdf='zathura'
alias img='sxiv -b -a'

alias fetch='neofetch --source ~/Pictures/ascii_arts/saitama'
