
;---------------------------------------
;		COLORS
;---------------------------------------
[colors]
bg = #2e3440
fg = #e5e9f0
grey = #4c566a
red = #bf616a
blue = #5e81ac
green = #a3be8c
yellow = #ebcb8b
teal = #8fbcbb
cyan = #88c0d0
purple = #b48ead
