;---------------------------------------
;		COLORS
;---------------------------------------
[colors]
bg = #2b303b
fg = #c0c5ce
grey = #c0c5ce
red = #bf616a
blue = #8fa1b3
green = #a3be8c
yellow = #ebcb8b
teal = #96b5b4
cyan = #81a2be
purple = #b48ead
