;---------------------------------------
;		COLORS
;---------------------------------------
[colors]
bg = #1d1f21
fg = #c5c8c6
grey = #707880
red = #a54242
blue = #5f819d
green = #8c9440
yellow = #f0c674
teal = #8abeb7
cyan = #81a2be
purple = #b294bb
