;---------------------------------------
;	     INCLUDE FILES
;---------------------------------------

include-file = ~/.config/polybar/colors/nord.ini
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/user_modules.ini

;---------------------------------------
;		GLOBAL
;---------------------------------------
[bar/tomorrow]
width = 100%
height = 30 
bottom = false
line-size = 3

background = ${colors.bg}
border-bottom-size = 1
border-bottom-color = ${colors.cyan}

;tray-detached = true
;tray-offset-x = -330

tray-position = right
tray-background = ${colors.bg} 

wm-restack = bspwm

;---------------------------------------
;		FONTS
;---------------------------------------
font-0 = Victor Mono Nerd Font:style=Bold:size=10;2
font-1 = Material Design Icons:size=11;3

;---------------------------------------
;	     MODULES LAYOUT
;---------------------------------------
modules-left = power sep1 bspwm sep memory cpu fs sep title
modules-center =  
modules-right = cmus spotify sep pulseaudio mic sep network sep time sep1
