;---------------------------------------
;	      BSPWM MODULE
;---------------------------------------
[module/bspwm]
type = internal/bspwm

format = <label-state> <label-mode>

ws-icon-default = 󰍹

label-focused-occupied = %icon%
label-focused-occupied-foreground = ${colors.purple}
label-focused-occupied-background = ${colors.bg}
label-focused-occupied-padding = 1

label-focused-urgent = %icon%
label-focused-urgent-foreground = ${colors.red}
label-focused-urgent-background = ${colors.bg}
label-focused-urgent-padding = 1

label-focused-empty = %icon%
label-focused-empty-foreground = ${colors.cyan}
label-focused-empty-background = ${colors.bg}
label-focused-empty-padding = 1

label-occupied = %icon%
label-occupied-foreground = ${colors.teal}
label-occupied-background = ${colors.bg}
label-occupied-padding = 1

label-urgent = %icon% 
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.bg}
label-urgent-padding = 1

label-empty = %icon%
;label-empty-foreground = ${colors.fg}
label-empty-background = ${colors.bg}
label-empty-padding = 1

label-monocle = " M "
label-tiled = " T "

label-tiled-foreground = ${colors.purple}
label-monocle-foreground = ${colors.red}


;---------------------------------------
;	   TIME MODULE
;---------------------------------------
[module/time]
type = internal/date

time = %H:%M
time-alt = %H:%M, %a %d

label = "󰅐 %time%"

format-foreground = ${colors.purple}
format-background = ${colors.bg}
format-padding = 0

;---------------------------------------
;	   AUDIO MODULE
;---------------------------------------
[bar]
fill = 絛
empty = 絛
indicator =  
; Nerd font :   ,  ⏽,  樂 籠 錄 , 雷 絛

[module/pulseaudio]
type = internal/pulseaudio
sink = 

click-right = pavucontrol
use-ui-max = false

format-volume = <label-volume> <bar-volume>

label-volume = 󰕾
label-muted = "󰖁 Muted "

format-volume-foreground = ${colors.fg}
format-volume-background = ${colors.bg}
format-muted-foreground = ${colors.red}
format-muted-background = ${colors.bg}

bar-volume-format = "%fill%%indicator%%empty%  "
bar-volume-width = 14
bar-volume-gradient = true

bar-volume-indicator = ${bar.indicator}
bar-volume-indicator-foreground = ${colors.fg}
bar-volume-indicator-font = 2

bar-volume-fill = ${bar.fill}
bar-volume-fill-foreground = ${colors.blue}
bar-volume-fill-font = 2

bar-volume-empty = ${bar.empty}
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.fg}
;---------------------------------------
;	   NETWORK MODULE
;---------------------------------------
[module/network]
type=internal/network
interface = eno1


label-disconnected = "󰞂 %ifname%"
label-connected = "󰞂 %ifname%"

format-connected-foreground = ${colors.yellow}
format-connected-background = ${colors.bg}
format-disconnected-foreground = ${colors.red}
format-disconnected-background = ${colors.bg}

;---------------------------------------
;	   CPU MODULE
;---------------------------------------
[module/cpu]
type = internal/cpu
interval = 0.5

format = <label>
format-prefix = "  󰭄"
format-prefix-foreground = ${colors.teal}

label = " %percentage%% "

;---------------------------------------
;	   MEMORY MODULE
;---------------------------------------
[module/memory]
type = internal/memory
interval = 2

format = <label>
format-prefix = "󰍛"
format-prefix-foreground = ${colors.cyan}

label = " %mb_used%"

;---------------------------------------
;	   FILESYSTEM MODULE
;---------------------------------------
[module/fs]
type = internal/fs

mount-0 = /
interval = 30
fixed-values = false


format-mounted = <label-mounted>
format-mounted-prefix = " 󰪣"
format-mounted-prefix-foreground = ${colors.purple}

label-mounted = " %used%"

;---------------------------------------
;	   SEPARATOR MODULE
;---------------------------------------
[module/sep]
type = custom/text
content = " | " 
content-foreground = ${colors.cyan}

[module/sep1]
type = custom/text
content = "|" 
content-foreground = ${colors.bg}
;---------------------------------------
;	   TITLE MODULE
;---------------------------------------

[module/title]
type = internal/xwindow

label = %title%
label-maxlen = 100

format-background = ${colors.bg}
format-foreground = ${colors.teal}

;---------------------------------------
;	   POWER MODULE
;---------------------------------------
[module/power]
type = custom/menu

expand-right = true

label-open = "  󰤁  "
label-open-background = ${colors.cyan}
label-open-foreground = ${colors.bg}

label-close = "  󰅚 "
label-close-background = ${colors.cyan}
label-close-foreground = ${colors.bg}

menu-0-0 = "  󰷛 "
menu-0-0-background = ${colors.cyan}
menu-0-0-foreground = ${colors.bg}
menu-0-0-exec = betterlockscreen -l blur

menu-0-1 = " 󰤄 "
menu-0-1-background = ${colors.cyan}
menu-0-1-foreground = ${colors.bg}
menu-0-1-exec = systemctl suspend

menu-0-2 = " 󰈆 "
menu-0-2-background = ${colors.cyan}
menu-0-2-foreground = ${colors.bg}
menu-0-2-exec = bspc quit

menu-0-3 = " 󰜉 "
menu-0-3-background = ${colors.cyan}
menu-0-3-foreground = ${colors.bg}
menu-0-3-exec = reboot

menu-0-4 = " 󰐥  "
menu-0-4-background = ${colors.cyan}
menu-0-4-foreground = ${colors.bg}
menu-0-4-exec = shutdown now

;---------------------------------------
;	   MENU MODULE
;---------------------------------------
[module/menu]
type = custom/text
content = 󰝘
content-font = 2
content-background = ${colors.cyan}
content-foreground = ${colors.bg}
content-padding = 2
click-left = rofi -show drun -location 1 -yoffset 30 -lines 15
