
;---------------------------------------
;	   MIC MODULE
;---------------------------------------
[module/mic]
type = custom/script
exec = ~/.config/polybar/scripts/mic.sh

tail = true
click-left = ~/.config/polybar/scripts/mic.sh --toggle &

format-background = ${colors.bg}
;format-foreground = ${colors.fg}

;---------------------------------------
;	   SPOTIFY MODULE
;---------------------------------------
[module/spotify]
type = custom/script

exec     = ~/.config/polybar/scripts/spotify.sh 
interval = 5
#tail     = true

label   = %output%
label-foreground = ${colors.green}

format  = <label>
format-prefix = "󰓇 " 
format-prefix-foreground = ${colors.green}

;---------------------------------------
;	   CMUS MODULE
;---------------------------------------
[module/cmus]
type = custom/script

exec       = ~/.config/polybar/scripts/cmus.sh
exec-if    = pgrep -x cmus
interval   = 5

label   = %output%
label-foreground = ${colors.green}

format  = <label>
format-prefix = "󰎆 " 
format-prefix-foreground = ${colors.green}
